name: Deploy

on:
  push:
    branches:
      - main
      - future
  schedule:
    - cron: '20 8 * * 1'

jobs:
  deployment:
    name: Build and deploy the image
    runs-on: ubuntu-latest
    container: docker
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Install the latest AWS CLI
        run: |
          apk add --no-cache python3 py3-pip
          pip3 install --upgrade pip
          pip3 install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900

      - name: Log in to Amazon public ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Log in to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the Alpine runner-terraform image
        uses: docker/build-push-action@v2
        with:
          file: ./alpine/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/future' }}
          tags: |
            ${{ secrets.PUBLIC_RUNNER_TERRAFORM_ECR_REPOSITORY_URL }}:${{ github.ref == 'refs/heads/main' && 'latest' || 'future' }}
            ghcr.io/spacelift-io/runner-terraform:${{ github.ref == 'refs/heads/main' && 'latest' || 'future' }}

      - name: Build and push the Debian runner-terraform image
        uses: docker/build-push-action@v2
        with:
          file: ./debian/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/future' }}
          tags: |
            ${{ secrets.PUBLIC_RUNNER_TERRAFORM_ECR_REPOSITORY_URL }}:debian
            ghcr.io/spacelift-io/runner-terraform:debian
